// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u23637707_HW01_API.Models;

#nullable disable

namespace u23637707_HW01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409063050_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u23637707_HW01_API.Models.Event", b =>
                {
                    b.Property<Guid>("Event_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TicketPricing")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Event_Id = new Guid("b7f9e2a1-3c45-4d67-8f90-123456789abc"),
                            Location = "HB",
                            TicketPricing = 50.0,
                            Title = "SRC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
